"""create players table

Revision ID: 04c39fdd933e
Revises: 61a9967bc0a2
Create Date: 2026-05-20 19:13:59.423642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '04c39fdd933e'
down_revision: Union[str, None] = '61a9967bc0a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
