"""create players table

Revision ID: 61a9967bc0a2
Revises: 
Create Date: 2026-05-20 19:12:12.893619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '61a9967bc0a2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('country', sa.String(length=3), nullable=True),
    sa.Column('gender', sa.String(length=1), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=True),
    sa.Column('current_elo', sa.Float(), nullable=False),
    sa.Column('matches_played', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_external_id'), 'players', ['external_id'], unique=True)
    op.create_index(op.f('ix_players_full_name'), 'players', ['full_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_players_full_name'), table_name='players')
    op.drop_index(op.f('ix_players_external_id'), table_name='players')
    op.drop_table('players')
    # ### end Alembic commands ###
