"""create matches table

Revision ID: 9757a926d64d
Revises: 04c39fdd933e
Create Date: 2026-05-20 20:06:20.224461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9757a926d64d'
down_revision: Union[str, None] = '04c39fdd933e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player1_id', sa.Integer(), nullable=False),
    sa.Column('player2_id', sa.Integer(), nullable=False),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.Column('match_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tournament', sa.String(length=120), nullable=False),
    sa.Column('surface', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('score', sa.String(length=50), nullable=True),
    sa.Column('aces_p1', sa.Integer(), nullable=True),
    sa.Column('aces_p2', sa.Integer(), nullable=True),
    sa.Column('breaks_p1', sa.Integer(), nullable=True),
    sa.Column('breaks_p2', sa.Integer(), nullable=True),
    sa.Column('points_p1', sa.Integer(), nullable=True),
    sa.Column('points_p2', sa.Integer(), nullable=True),
    sa.Column('external_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player1_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['player2_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_external_id'), 'matches', ['external_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_matches_external_id'), table_name='matches')
    op.drop_table('matches')
    # ### end Alembic commands ###
